[package]
name = "dijkstra_map_gd"
version = "0.1.0"
authors = ["Astrale", "Matej Sloboda"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
fnv = "1.0.7"
gdnative = "0.11.0"
dijkstra_map = { path = "../dijkstra-map" }

[build-dependencies]
gdnative-doc = "0.0.6"
